[package]
name = "gnawex_core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-postgres = { workspace = true }
postgres-types = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
