[package]
name = "gnawex"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
gnawex_core = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
