[book]
authors = ["Sek Un"]
language = "en"
multilingual = false
src = "src"
title = "GNAWEX Documentation"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js =["mermaid.min.js", "mermaid-init.js"]
