name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test-db-migrations:
    runs-on: ubuntu-22.04

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGHOST: localhost
      PGPORT: 5432

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= loony-tools:pr9m4BkM/5/eSTZlkQyRt57Jz7OMBxNSUiMC4FkcNfk= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://cache.iog.io https://cache.zw3rk.com https://cache.nixos.org/

      - name: Create gnawex_db
        run: createdb gnawex_db

      - name: Checkout pgtap
        uses: actions/checkout@v2
        with:
          repository: theory/pgtap
          path: pgtap
          ref: v1.2.0

      - name: Install pgtap
        working-directory: pgtap
        run: make && psql --host localhost --username postgres --dbname gnawex_db --file sql/pgtap.sql

      - name: Check if DB migrations work
        run: |
          nix develop .#devShells.x86_64-linux.ci-db \
            --command sqitch deploy

      - name: Check if DB migrations revert work
        run: |
          nix develop .#devShells.x86_64-linux.ci-db \
            --command sqitch revert

      # TODO: Run pg_tap tests
