name: Deploy documentation

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v2

      - name: Setup Nix
        uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: |
            trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
            substituters = https://hydra.iohk.io https://cache.nixos.org/

      - run: nix flake show

      - name: Install dependencies
        run: |
          nix develop .#devShells.x86_64-linux.ci \
            --command mix do local.hex --force, deps.get

      - uses: actions/cache@v2
        name: Cache /nix/store
        with:
          path: /nix/store
          key: ${{ runner.os }}-${{ hashFiles('flake.lock') }}

      - name: Build docs
        run: nix develop .#devShells.x86_64-linux.ci --command mix docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/doc

